name: Build Blog from Issues

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, labeled, unlabeled, closed]

permissions:
  contents: write

# ← 同時実行を抑止（open と label が同時に来ても片方に）
concurrency:
  group: blog-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # ← ここに移動：全ステップから参照できる
    env:
      REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LABEL: blog
      BLOG_DIR: blog
      SITE_BASE: /

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ← rebase/pull が安全に

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build blog from issues
        run: |
          set -euo pipefail
          echo "INFO: Node version: $(node -v)"
          node scripts/build-blog.mjs

      - name: Commit & Push generated files
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "INFO: 最新取得 & rebase"
          git fetch origin
          git pull --rebase origin main || true

          echo "INFO: 生成物をステージング"
          git add "$BLOG_DIR" rss.xml || true

          echo "INFO: 変更件数: $(git status --porcelain | wc -l)"
          git commit -m "chore(blog): rebuild from issues [skip ci]" || echo "no changes"

          echo "INFO: push 実行"
          git push
